# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inicializando.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 3, 591, 421))
        self.label.setStyleSheet("border-image: url(:/Back/Footer.webp);\n"
"background-color: rgb(0, 100, 147);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 23, 551, 381))
        self.label_2.setStyleSheet("background-color: rgba(185, 185, 185, 100);\n"
"border-radius:18px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 353, 551, 51))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-bottom-color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255,100);\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 203, 141, 191))
        self.label_4.setStyleSheet("border-image: url(:/newPrefix/part1.webp);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.QProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.QProgressBar.setGeometry(QtCore.QRect(167, 365, 271, 23))
        self.QProgressBar.setStyleSheet("QProgressBar{text-align:center;\n"
"}\n"
"QProgressBar::chunk{background-color: qlineargradient(spread:pad, x1:0.75, y1:0.46, x2:0, y2:0.784, stop:0 rgba(0, 68, 100, 255), stop:1 rgba(0, 174, 255, 255));};\n"
"\n"
"\n"
"")
        self.QProgressBar.setProperty("value", 24)
        self.QProgressBar.setObjectName("QProgressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import Background_BoasVindas_rc
import Em_pe_rc
